name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
