name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
    - name: Format
      uses: actions-rs/cargo@v1
      run: rustfmt --check
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
