name: Publish

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build documentation
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --manifest-path=soco/Cargo.toml
    - name: Move documentation
      run: mv ./soco/target/doc ./dist/doc
    - name: Prepare files
      run: sh ./scripts/setup.sh
    - name: Compile LaTeX sources
      uses: xu-cheng/latex-action@v2
      with:
        pre_compile: tlmgr update --self && tlmgr update --all
        root_file: |
          docs/thesis.tex
    - name: Move PDFs
      run: mv ./*.pdf ./dist
    - name: Move readme
      run: cp ./README.md ./dist/index.md
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist
        allow_empty_commit: true
        force_orphan: true
        enable_jekyll: true
