name: Publish

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Move readme
        run: |
          cp ./README.md ./dist/index.md
          cp ./implementation/src/algorithms/README.md ./dist/algorithms.md
      - name: Compile and Deploy
        uses: jonhue/pubtex-action@main
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          files: |
            thesis/main.tex
            thesis/slides.tex
          handouts: |
            thesis/slides.tex
