name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Login
      uses: actions-rs/cargo@v1
      with:
        command: login
        args: ${CRATES_API_TOKEN}
      env:
        CRATES_API_TOKEN: ${{secrets.CRATES_API_TOKEN}}
    - name: Publish
      uses: actions-rs/cargo@v1
      with:
        command: publish
